-- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  role text,
  email text,
  
  -- Student specific
  apaar_id text,
  register_no text,
  
  -- Faculty specific
  faculty_id text,
  
  -- Admin specific
  admin_id text
);

-- Enable security
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for certificates
create table certificates (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Connects to the user via their Apaar ID / Hashed ID as requested
  user_hashed_id text, 
  
  certificate_number text,
  status integer default 0 -- 0 = unverified, 1 = verified
);

alter table certificates enable row level security;

create policy "Certificates are viewable by everyone." on certificates
  for select using (true);
